name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - run: export -p
    - name: apt-get install ninja-build
      run: sudo apt-get install python3 python3-pip ninja-build -y
    - name: python -m pip install --upgrade pip
      run: pip3 install --upgrade pip
    - name: install setuptools
      run: pip3 install --upgrade setuptools
    - name: install meson
      run: python3 -m pip install --user meson
    - name: meson build
      run: meson build 
    - name: ninja -C build
      run: ninja -C build
    - name: 测试
      run: ./build/hq -h
